language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

script: skip

jobs:
  include:
    - stage: test
      script: gradle :core:check
    - stage: test
      script: gradle :observers:check
    - stage: test
      script: gradle :algorithms:check
    - stage: test
      script: gradle :models:check

before_install:
  - git clone https://github.com/wkramer/repo.git

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
